---
- name: Install and configure Kubernetes components
  hosts: kubernetes
  gather_facts: true
  become: true

  roles:
    - role: crio
    - role: kubelet
    - role: kubeadm

- name: Initialize Kubernetes control plane
  hosts: k8s_masters
  become: true

  roles:
    - role: kubeadm_init
    - role: calico

- name: Join workers to cluster
  hosts: k8s_workers
  become: true

  roles:
    - role: kubeadm_join
