---
- name: Restart kubelet
  ansible.builtin.systemd:
    name: kubelet
    state: restarted
    daemon_reload: true
    enabled: true

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
