---
- name: Initialize Kubernetes cluster
  ansible.builtin.command: >
    kubeadm init
    --pod-network-cidr=192.168.0.0/16
    --cri-socket=unix:///var/run/crio/crio.sock
  args:
    creates: /etc/kubernetes/admin.conf
  register: kubeadm_init_output
  become: true

- name: Create .kube directory
  ansible.builtin.file:
    path: /root/.kube
    state: directory
    mode: "0755"

- name: Copy admin.conf
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    remote_src: true
    owner: root
    group: root
    mode: "0644"

- name: Get join command
  ansible.builtin.command: kubeadm token create --print-join-command
  register: kubeadm_init_join_command_raw
  changed_when: false

- name: Set join command fact
  ansible.builtin.set_fact:
    kubeadm_init_join_command: "{{ kubeadm_init_join_command_raw.stdout }}"
